### PR TITLE
Feat/gh399/update appicons

### LINKED ISSUE #399: [BUG]: Update AppIcons with new Logo
**Describe the bug**
Change App Icons and Launcher Icons to use the new logo.

### PR DESCRIPTION
**Pull request by sarahaudina**
close #399

### CODE REVIEW

**Comment by wizlif** [comment]
Thanks for the update, seems you didn’t use https://pub.dev/packages/flutter_launcher_icons . 
You can simply update the [assets/images/icons/app_icon.png](
https://github.com/CollActionteam/collaction_app/blob/development/assets/images/icons/app_icon.png) to the new icon then run `flutter pub run flutter_launcher_icons` to generate all icons.

**Comment by sarahaudina** [comment]
Oh right, thanks for mentioning it @wizlif . I will update to use the lib today.

**Comment by sarahaudina** [comment]
I had to change remove_alpha_ios to false, so the icon's corner not black colored on ios. Let me know if this will be a problem @wizlif . Thanks.

**Review by wizlif — DISMISSED** [review]
Looks awesome

**Comment by wizlif** [comment]
Btw @, just another thought popped. Can't we fill the curving transparent side and use the original configuration. Coz I'm sure on android the border radius on the icon is defined by the system e.g by a theme. [Not sure about iOs].

What do you think ??

**Review by wizlif — APPROVED** [review]

**Pull request merged**
