### PR TITLE
APP-23 Splash Screen

### PR DESCRIPTION
**Pull request by arun-muralidharan**
Added logo image set and edited launch_background.xml.

Splash screen now works for android.

I do not have access to a Mac. Someone who does can do the same for iOS. Here's Flutter's guide for it: https://flutter.dev/docs/development/ui/advanced/splash-screen

### CODE REVIEW

**Comment by rubenhorn** [comment]
@arun-muralidharan The icon will be overwritten by [this image asset](https://github.com/CollActionteam/collaction_app/blob/feat/app-23/splash-screen/assets/icon/icon.png). (s. [CI workflow](https://github.com/CollActionteam/collaction_app/blob/feat/app-23/splash-screen/.github/workflows/ci.yml#L103))  

But it looks like it's the same size logo, right?

**Review by Xazin — APPROVED** [review]

**Comment by Xazin** [comment]
> @arun-muralidharan The icon will be overwritten by [this image asset](https://github.com/CollActionteam/collaction_app/blob/feat/app-23/splash-screen/assets/icon/icon.png). (s. [CI workflow](https://github.com/CollActionteam/collaction_app/blob/feat/app-23/splash-screen/.github/workflows/ci.yml#L103))
> 
> But it looks like it's the same size logo, right?

Seems to me they should be identical?

**Comment by arun-muralidharan** [comment]
I had to replace the image set because the generated ones were smaller. With the generated icons, the splash screen image seems to be the same size as the launch icon.

**Comment by rubenhorn** [comment]
But then it will be replaced by the generated one during CI build.
I recommend using a separate vector drawable.
You can export it from Figma as SVG and convert it to drawable XML using [an online tool](https://svg2vector.com/).

**Comment by arun-muralidharan** [comment]
Okay! I'll look into this.

**Comment by arun-muralidharan** [comment]
@rubenhorn @Xazin I added a separate image set for the splash logo.

**Review by Xazin — APPROVED** [review]

**Pull request merged**
