### PR TITLE
chore: rebase profile pic and edit bio

### PR DESCRIPTION
**Pull request by Xazin**

### CODE REVIEW

**Review by wizlif — APPROVED** [review]
LGTM!

**Comment by Xazin** [comment]
@glitchpop-frenzy Do you maybe have time to fix this? I guess we didn't completely finish and I also forgot about it. xD

**Comment by glitchpop-frenzy** [comment]
We fixed this. Yash's profile was logged in my device hence the commit is in his name.

**Comment by Xazin** [comment]
Analyzer and tests are failing @glitchpop-frenzy that's why I asked you haha

**Pull request merged**
