### PR TITLE
Feature/6 contact form

### PR DESCRIPTION
**Pull request by MaschavanderMarel**

### CODE REVIEW

**Comment by rubenhorn** [comment]
Review:

- Code compiles
- Tests written and are passing
- Form validation

Suggestions:

- Navigate back (pop route) after the form was submitted (!) submitted
- Change snackbar to reflect final submission result (success/failure)
- Only hide snackbar after submission result was displayed (success/failure)
- Mock submission of feedback by printing it to the form data

Otherwise the PR is ok and could be merged :)

**Review by rubenhorn — COMMENTED** [review]
Review: 

- Code compiles
- Tests written and are passing
- Form validation

Suggestions:

- Navigate back (pop route) after the form was submitted (!) submitted
- Change snackbar to reflect final submission result (success/failure)
- Only hide snackbar after submission result was displayed (success/failure)
- Mock submission of feedback by printing it to the form data

Otherwise the PR is ok and could be merged :)

**Comment by MaschavanderMarel** [comment]
> Review:
> 
> * Code compiles
> * Tests written and are passing
> * Form validation
> 
> Suggestions:
> 
> * Navigate back (pop route) after the form was submitted (!) submitted  MM: Do you mean after the mock submission?
> * Change snackbar to reflect final submission result (success/failure) MM: Instead of the processing data message?
> * Only hide snackbar after submission result was displayed (success/failure) MM: The snackbar currently already hides after a second. Do you mean something else?
> * Mock submission of feedback by printing it to the form data: Do you mean putting the email address and feedback in the FormData class from the dart:html library?
> 
> Otherwise the PR is ok and could be merged :)

**Comment by rubenhorn** [comment]
To address your questions:
> Navigate back (pop route) after the form was submitted (!) submitted MM: Do you mean after the mock submission?

Yes.

> Change snackbar to reflect final submission result (success/failure) MM: Instead of the processing data message?
> [...] The snackbar currently already hides after a second. Do you mean something else?

We don't have a ux flow for this yet, but this is how I imagine it:
 - Form is submitted and snackbar "processing" is shown indefinitely (do not hide automatically)
 - If an error occurred, change the snackbar to "error" and hide it after about one second
 - If the form was successfully submitted, change the snackbar to "success" and navigate back (pop route)
 - (The form should only be editable initially and after an error, so disable it on "submit" and enable it on "error")

> Do you mean putting the email address and feedback in the FormData class from the dart:html library?

I was just thinking we could have a simple placeholder for `Future submitForm(email, message)` that waits for a few seconds and then just calls `print(...)` using the form data.

**Comment by MaschavanderMarel** [comment]
@rubenhorn , I've implemented your suggestions. Could you please review again? tx,

**Review by rubenhorn — APPROVED** [review]

**Pull request merged**
